export const INIT_STORE = 'INIT_STORE';

export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';

export const FETCH_ROOM_START = 'FETCH_ROOM_START';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_ERROR = 'FETCH_ROOM_ERROR';
export const FETCH_ROOM_END = 'FETCH_ROOM_END';
export const ROOM_UNREAD_MESSAGES_SET = 'ROOM_UNREAD_MESSAGES_SET';
export const ROOM_UNREAD_MESSAGES_DROP = 'ROOM_UNREAD_MESSAGES_DROP';
export const ROOM_UNREAD_MESSAGES_INCREMENT = 'ROOM_UNREAD_MESSAGES_INCREMENT';

export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const FETCH_MESSAGES_END = 'FETCH_MESSAGES_END';
export const ADD_MESSAGE_TO_SEND = 'ADD_MESSAGE_TO_SEND';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_END = 'FETCH_USERS_END';
export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const READ_MESSAGES = 'READ_MESSAGES';
export const READ_MY_MESSAGES = 'READ_MY_MESSAGES';
export const RENEW_MESSAGE_STATE = 'RENEW_MESSAGE_STATE';

export const NETWORK_WENT_DOWN = 'NETWORK_WENT_DOWN';
export const NETWORK_WENT_UP = 'NETWORK_WENT_UP';
